baseURL = 'https://nelsonwells.com'
languageCode = 'en-us'
title = 'Nelson Wells'
theme = 'ndwbeautifulhugo'

[Params]
    subtitle = 'Programming and other distractions'
    useHLJS = true
    readingTime = true
    showRelatedPosts = true

[[menu.main]]
    name = "Projects"
    url = "projects"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

 [Author]
    name = 'Nelson Wells'
    github = 'nelsonwellswku'
    linkedin = 'nelsonwellswku'
    youtube = 'nelsonwellswku'
