baseURL = 'https://nelsonwells.com'
locale = 'en-US'
title = 'Nelson Wells'
theme = 'beautifulhugo'

[Params]
    subtitle = 'Programming and other distractions'
    useHLJS = true
    readingTime = true
    showRelatedPosts = true

[[menu.main]]
    name = "Projects"
    url = "projects"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3

[Params.author]
    name = 'Nelson Wells'
    github = 'nelsonwellswku'
    linkedin = 'https://linkedin.com/in/nelsonwellswku'
    youtube = 'nelsonwellswku'
